Feature/timer view
nzambonivergara/intention-timer pull request #5
Opened 2021-07-30 23:09 UTC by jphorner

Thank you for pushing your code!
**What (if any) features are you implementing?**
- Added warning message when a category is not selected
- Added helper function to display timer if no errors occur during form submission

**What (if anything) did you refactor?**
- Added new div to the HTML for the category warning since it is separate from the function which evaluates field values
- Invoked timer view function inside the 'else' statement of submitForm()
- Commented out return statement within 'else if' statement to allow multiple field errors to appear

**Were there any issues that arose?**
- The new showTimerView function works fine, but the event listener is attached to the form container
- This means that currently, clicking within the timer view reverts the page to the form view

**Is there anything that you need from your teammate?**
- If time allows, maybe changing 'toggle' in showTimerView to a simple add/remove.hidden method would solve the issue above?

**Any other comments, questions, or concerns?**
- Y'all are awesome. Thanks for working so hard on this.

**Collaborators**

2021-07-30 23:32 UTC, nzambonivergara commented on main.js
> +      categoryWarning.innerHTML = `<img src="./assets/warning.svg" alt="warning sign" id="warning"> A category is required.`;
Let's remember to make sure that the message does not disappear once user clicks a category button.

2021-07-30 23:34 UTC, nzambonivergara commented on main.js
> +function showTimerView() {
Should we toggle or just add/remove classes?

2021-07-30 23:35 UTC, nzambonivergara commented on main.js
> +function showTimerView() {
Should we toggle or just add/remove classes?

2021-07-30 23:36 UTC, nzambonivergara commented on styles.css
> +  padding: 0px;
Let's try to keep our units consistent throughout and change our px to rem?

2021-07-30 23:39 UTC, nzambonivergara commented on styles.css
> +  cursor: pointer;
Could we put this in all the buttons by using the the button tag selector?

2021-07-30 23:43 UTC, nzambonivergara commented
The timer view looks great!! Just added some minor comments for us to remember changes we want to include.

2021-07-30 23:46 UTC, nzambonivergara requested changes
We will continue working on this functionality so we don't want to close the branch yet.

2021-07-31 22:09 UTC, jphorner commented
Thanks for the feedback! I'm working with Nolan and we'll make a PR for the latest commits soon.

2021-07-31 22:09 UTC, closed without merging